Invoke-WebRequest "https://raw.githubusercontent.com/mendisuissa/AutoPilot/main/AutoPilot%20Steps.txt" -OutFile ./"AutoPilot%20Steps.txt" 
Invoke-WebRequest "https://raw.githubusercontent.com/mendisuissa/AutoPilot/main/Get-AutopilotDiagnostics.ps1" -OutFile .\"Get-AutopilotDiagnostics.ps1"
Invoke-WebRequest "https://raw.githubusercontent.com/mendisuissa/AutoPilot/main/Show-WiFi.bat" -OutFile .\"Show-WiFi.bat"
Invoke-WebRequest "https://raw.githubusercontent.com/mendisuissa/AutoPilot/main/Get-WindowsAutoPilotInfo.ps1" -OutFile .\"Get-WindowsAutoPilotInfo.ps1"
Invoke-WebRequest "https://raw.githubusercontent.com/mendisuissa/AutoPilot/main/Upload-AzureAD-Online.bat" -OutFile .\"Upload-AzureAD-Online.bat"
Invoke-WebRequest "https://raw.githubusercontent.com/mendisuissa/AutoPilot/main/Upload-Online.bat" -OutFile .\"Upload-Online.bat"
